############################################################
###### This is a "VSCode REST Client" Extention      #######
############################################################

### List all messages
GET http://localhost:3000/messages


### Create a new message
POST http://localhost:3000/messages
Content-type: application/json

{
  "content": "3rd new message created!"
}

### Get a particular message via id
GET http://localhost:3000/messages/823